# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 7.1"
gem "puma", ">= 5.0"
gem "octokit", "~> 7.0"
gem "dotenv-rails", "~> 3.1"
gem "pg", "~> 1.5"
gem "rack-cors"

group :development do
  gem "debug", require: false
  gem "listen", "~> 3.10"
end
